#!/bin/sh
exec 2>&1

. /etc/envvars

SANECONF="/etc/sane.d/saned.conf"
DLLCONF="/etc/sane.d/dll.conf"

# set ACL from environment variable
if [ -z "${SANED_ACL}" ]; then
  SANED_ACL="localhost"
fi

grep -q ^${SANED_ACL}$ ${SANECONF}
if [ ${?} -ne 0 ]; then
  echo ${SANED_ACL} >> ${SANECONF}
fi

# Limit data portrange to 10000 - 10001
sed -i 's/^#\s*data_portrange\s*=\s*.*$/data_portrange = 10000 - 10001/g' ${SANECONF}

# Set the DLL (optional)
if [ -n "${SANED_DLL}" ]; then
  grep -q ^${SANED_DLL}$ ${DLLCONF}
  if [ ${?} -ne 0 ]; then 
    echo ${SANED_DLL} >> ${DLLCONF}
  fi
fi

# Set the default log level (if not set)
if [ -z "${SANED_LOG_LEVEL}" ]; then
  SANED_LOG_LEVEL = 2
fi

sv start dbus || exit 1

exec saned -d ${SANED_LOG_LEVEL}
